services:
  postgres:
    image: postgres:18-alpine
    container_name: jadwalin_db
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/
    networks:
      - jadwalin_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: jadwalin_pgadmin
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - jadwalin_network
    depends_on:
      - postgres

  redis:
    image: redis:7-alpine
    container_name: jadwalin_redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    networks:
      - jadwalin_network

volumes:
  postgres_data:
  pgadmin_data:
  redis_data:

networks:
  jadwalin_network:
    driver: bridge
